import { Product } from '../../stores/myai-products-store/product-store';

export const trendingProducts: Product[] = [
  {
    delivery: 'Free returns to Sweden',
    link: 'https://amzn.to/3wsUu29',
    price: '$16.96',
    source: 'Nook Theory',
    thumbnail: 'https://m.media-amazon.com/images/I/8127dPVLqTL._AC_SL1500_.jpg',
    title: '4-Pack Bamboo Fiber Dinner Plates',
    rating: 4.6,
    reviews: 311,
  },
  {
    delivery: 'Delivers to Sweden',
    link: 'https://amzn.to/3wu4b0n',
    price: '$21.59',
    old_price: '23.99',
    source: 'Stanley',
    thumbnail: 'https://m.media-amazon.com/images/I/51oZZXH8EGL._AC_SL1500_.jpg',
    title: 'Stanley GO The Quick Flip GO Bottle',
    rating: 4.6,
    reviews: 12308,
  },
  {
    delivery: 'Delivers to Sweden',
    link: 'https://amzn.to/4dwK81V',
    price: '$59.95',
    source: 'Cuisinart',
    thumbnail: 'https://m.media-amazon.com/images/I/61FO+YCV+eL._AC_SL1175_.jpg',
    title: 'CUISINART Coffee Grinder, Electric Burr One-Touch Automatic Grinder',
    rating: 4.3,
    reviews: 42684,
  },
  {
    delivery: '$14.23 shipping to Sweden',
    link: 'https://amzn.to/3Wwunlp',
    price: '$95.00',
    source: 'Michael Kors',
    thumbnail: 'https://m.media-amazon.com/images/I/71-32BOYPrL._AC_SX522_.jpg',
    title: 'Michael Kors Oversized Slim Runway Watch',
    rating: 4.7,
    reviews: 11165,
  },
];

export const summerProducts: Product[] = [
  {
    delivery: '$14.84 Shipping to Sweden',
    link: 'https://amzn.to/4dz4K9J',
    price: '$16.99',
    source: 'Glacio',
    thumbnail: 'https://m.media-amazon.com/images/I/71Y65k1DlHL._AC_SL1500_.jpg',
    title: ' Large Silicone Ice Cube Mold Combo - Durable Flexible Ice Maker for Whiskey, Cocktails - Perfect for Craft Ice, Whiskey Ice Balls, and Cocktail Ice Cubes',
    rating: 4.4,
    reviews: 12385,
  },
  {
    delivery: '$16.56 Shipping to Sweden',
    link: 'https://amzn.to/3WwBg6z',
    price: '$20.99',
    source: 'Jartinle',
    thumbnail: 'https://m.media-amazon.com/images/I/71piHMIZTRL._AC_SL1500_.jpg',
    title: 'Jartinle Mid Century Modern Boho Abstract Throw Pillow Covers 18x18 Set of 4',
    rating: 4.5,
    reviews: 962,
  },
  {
    delivery: '$17.49 Shipping to Sweden',
    link: 'https://amzn.to/3Wwxnyb',
    price: '$19.68',
    source: 'Homestockplus',
    thumbnail: 'https://m.media-amazon.com/images/I/71WeRKdVX7L._AC_SL1500_.jpg',
    title: '8 Homestockplus 9 Inch Dinner Plates,BPA-Free Wheat Straw Plates,Off White Plate Set Dishwasher and Microwave Safe Plates',
    rating: 4.6,
    reviews: 487,
  },
  {
    delivery: '$65.27 Shipping to Sweden',
    link: 'https://amzn.to/3Qw7NFJ',
    price: '$129.00',
    old_price: '149.99',
    source: 'SWOOC',
    thumbnail: 'https://m.media-amazon.com/images/I/5111Jzb6PKL._AC_SL1000_.jpg',
    title: 'Reclaimed Giant Tower Game (Weather Resistant) 60 Blocks + Storage Crate/Outdoor Game Table',
    rating: 4.7,
    reviews: 538,
  },
];