import { Product } from '../../stores/myai-products-store/product-store';

export const trendingProducts: Product[] = [
  {
    delivery: 'Free returns to Sweden',
    link: 'https://amzn.to/3wsUu29',
    price: '$16.96',
    source: 'Nook Theory',
    thumbnail: 'https://m.media-amazon.com/images/I/8127dPVLqTL._AC_SL1500_.jpg',
    title: '4-Pack Bamboo Fiber Dinner Plates',
    rating: 4.6,
    reviews: 311,
  },
  {
    delivery: 'Delivers to Sweden',
    link: 'https://amzn.to/3wu4b0n',
    price: '$21.59',
    old_price: '23.99',
    source: 'Stanley',
    thumbnail: 'https://m.media-amazon.com/images/I/51oZZXH8EGL._AC_SL1500_.jpg',
    title: 'Stanley GO The Quick Flip GO Bottle',
    rating: 4.6,
    reviews: 12308,
  },
  {
    delivery: 'Delivers to Sweden',
    link: 'https://amzn.to/4dwK81V',
    price: '$59.95',
    source: 'Cuisinart',
    thumbnail: 'https://m.media-amazon.com/images/I/61FO+YCV+eL._AC_SL1175_.jpg',
    title: 'CUISINART Coffee Grinder, Electric Burr One-Touch Automatic Grinder',
    rating: 4.3,
    reviews: 42684,
  },
  {
    delivery: '$14.23 shipping to Sweden',
    link: 'https://amzn.to/3Wwunlp',
    price: '$95.00',
    source: 'Michael Kors',
    thumbnail: 'https://m.media-amazon.com/images/I/71-32BOYPrL._AC_SX522_.jpg',
    title: 'Michael Kors Oversized Slim Runway Watch',
    rating: 4.7,
    reviews: 11165,
  },
];

export const discountedProducts: Product[] = [
  {
    delivery: 'Free returns to Sweden',
    link: 'https://amzn.to/3wsUu29',
    price: '$16.96',
    source: 'Nook Theory',
    thumbnail: 'https://m.media-amazon.com/images/I/8127dPVLqTL._AC_SL1500_.jpg',
    title: '4-Pack Bamboo Fiber Dinner Plates',
    rating: 4.6,
    reviews: 311,
  },
  {
    delivery: 'Delivers to Sweden',
    link: 'https://amzn.to/3wu4b0n',
    price: '$21.59',
    old_price: '23.99',
    source: 'Stanley',
    thumbnail: 'https://m.media-amazon.com/images/I/51oZZXH8EGL._AC_SL1500_.jpg',
    title: 'Stanley GO The Quick Flip GO Bottle',
    rating: 4.6,
    reviews: 12308,
  },
  {
    delivery: 'Delivers to Sweden',
    link: 'https://amzn.to/4dwK81V',
    price: '$59.95',
    source: 'Cuisinart',
    thumbnail: 'https://m.media-amazon.com/images/I/61FO+YCV+eL._AC_SL1175_.jpg',
    title: 'CUISINART Coffee Grinder, Electric Burr One-Touch Automatic Grinder',
    rating: 4.3,
    reviews: 42684,
  },
  {
    delivery: '$14.23 shipping to Sweden',
    link: 'https://amzn.to/3Wwunlp',
    price: '$95.00',
    source: 'Michael Kors',
    thumbnail: 'https://m.media-amazon.com/images/I/71-32BOYPrL._AC_SX522_.jpg',
    title: 'Michael Kors Oversized Slim Runway Watch',
    rating: 4.7,
    reviews: 11165,
  },
];